### PR TITLE
chore(documantation): add metrics path to readme doc

### PR DESCRIPTION
**Pull request by eranamrani**
- [x] Contains documentation

### CODE REVIEW

**Comment by qlikossbuild** [comment]
Hi, and thanks for contributing!

Note: If you are part of Qlik R&D, you can apply to the `open-source` team in our _internal_ GitHub organization.

Before we can handle your pull request we need you to sign our contributor license agreement.
This is a one-time process and enables you to contribute without hassle to any of the qlik-oss repositories in the future.

And it only takes a few minutes! Here are some useful links to get you started:

* [Sign the CLA](https://github.com/qlik-oss/open-source/blob/master/sign-cla.md#sign-the-cla)
* [Rationale behind the CLA](https://github.com/qlik-oss/open-source/blob/master/cla-rationale.md)
* [Qlik R&D Open Source repository](https://github.com/qlik-oss/open-source#open-source-at-qlik-rd)
* [Official Slack team](http://branch.qlik.com/slack)

Having troubles? Feel free to reach out to us either here or on Slack!

**Note:** Once the CLA is sorted, you should rebase/touch this pull request to trigger an update of this CLA status.

**Comment by hairyhenderson** [comment]
Not sure why `cla/verification` is failing - the CLA is clearly present: https://github.com/qlik-oss/open-source/blob/master/contributors/eranamrani.md

@peol do you know what's up?

**Comment by eranamrani** [comment]
@hairyhenderson any progress?

**Comment by hairyhenderson** [comment]
Sorry @eranamrani - lost track of this one. I'll try to find out why the CLA verification is failing.

In the meantime do you think you could amend your commit re-push so the CI can re-trigger?

**Comment by eranamrani** [comment]
Hi, i can't see the build changes when i upgrade the package, why is the
version still 2.0.0 and not bumped?

**Comment by hairyhenderson** [comment]
@eranamrani Sorry, I didn't make a release of this. I'll cut one now!

**Comment by hairyhenderson** [comment]
@eranamrani https://github.com/qlik-oss/http-metrics-middleware/releases/tag/v2.1.0 is published - sorry for the delay!

**Comment by eranamrani** [comment]
I still can't find the new release version (2.1.0), please let me know when
all of it is fixed I need it urgently

**Comment by hairyhenderson** [comment]
@eranamrani I published that release when I made that comment yesterday. It's listed on npm too: https://www.npmjs.com/package/http-metrics-middleware

**Comment by eranamrani** [comment]
Hi Dave,
I can see the release now, thanks for your cooperation.
looking forward to contributing more :)

Thanks for the help

**Pull request merged**
